{{- if .Values.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kellnr.fullname" . }}
  labels:
    {{- include "kellnr.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kellnr.labels" . | nindent 6 }}
  minAvailable: {{ .Values.pdb.minAvailable }}
{{- end }}