{{- if and .Values.secret.enabled (not .Values.secret.useExisting) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | quote }}
type: Opaque
stringData: 
{{- include "kellnr.envVars" . | nindent 2 }}
{{- end }}